 * Starting OpenBSD Secure Shell server sshd
   ...done.
INFO:circe.py:Using base script preagg.py
DEBUG:circe.py:starting the input monitoring process
DEBUG:circe.py:starting the output monitoring process
3
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_2jobth2#78099124-2#37810485-2#89105181-2#16917738", "unix_time": 1620589266.0558164}
INFO:ccdag_utils.py:runtime_stat:{"task_name": "preagg3", "event": "queue_start_process", "filename": "score3b_preagg3_2jobth2#78099124-2#37810485-2#89105181-2#16917738", "unix_time": 1620589266.3078752}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_2jobth2#78099124-2#37810485-2#89105181-2#16917738", "unix_time": 1620589266.9382205}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 144, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1042, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 153, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5b228eb470>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='10.100.92.70', port=6100): Max retries exceeded with url: /post-dict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b228eb470>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/jupiter/build/app_specific_files/preagg.py", line 96, in task
    response =  requests.post(url, headers = hdr,data = json.dumps(payload))
  File "/usr/lib/python3/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.100.92.70', port=6100): Max retries exceeded with url: /post-dict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5b228eb470>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/jupiter/build/app_specific_files/preagg.py", line 105, in task
    job_dict = {'2':[sample1[0],sample2[0]]}
IndexError: list index out of range

INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_2jobth2#78099124-2#37810485-2#89105181-2#16917738", "unix_time": 1620589273.976038}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_2jobth2#63940447-2#67681670-2#75343955-2#86901502", "unix_time": 1620589434.63511}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_2jobth2#63940447-2#67681670-2#75343955-2#86901502", "unix_time": 1620589435.6786246}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_2jobth2#63940447-2#67681670-2#75343955-2#86901502", "unix_time": 1620589443.5998206}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_1jobth2#97466216-2#64678239-2#23783679-2#37929010", "unix_time": 1620589523.2742376}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_1jobth2#97466216-2#64678239-2#23783679-2#37929010", "unix_time": 1620589524.229504}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_1jobth2#97466216-2#64678239-2#23783679-2#37929010", "unix_time": 1620589532.2394168}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_2jobth2#60697141-2#90817475-2#66514921-2#27651698", "unix_time": 1620589578.940592}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_2jobth2#60697141-2#90817475-2#66514921-2#27651698", "unix_time": 1620589579.8357365}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_2jobth2#60697141-2#90817475-2#66514921-2#27651698", "unix_time": 1620589587.908251}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_3jobth2#05908150-2#91646273-2#08481825-2#28043154", "unix_time": 1620589638.3859146}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_3jobth2#05908150-2#91646273-2#08481825-2#28043154", "unix_time": 1620589639.409874}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_3jobth2#05908150-2#91646273-2#08481825-2#28043154", "unix_time": 1620589647.5094388}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_4jobth2#48644987-2#50031571-2#53356595-2#97116701", "unix_time": 1620589720.991995}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_4jobth2#48644987-2#50031571-2#53356595-2#97116701", "unix_time": 1620589722.007432}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_4jobth2#48644987-2#50031571-2#53356595-2#97116701", "unix_time": 1620589729.9953678}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_5jobth2#03701482-2#90147438-2#95019200-2#96278549", "unix_time": 1620589804.5093942}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_5jobth2#03701482-2#90147438-2#95019200-2#96278549", "unix_time": 1620589805.6088088}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_5jobth2#03701482-2#90147438-2#95019200-2#96278549", "unix_time": 1620589813.5986497}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_6jobth2#92477709-2#06433455-2#57715521-2#36985629", "unix_time": 1620589933.1960633}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_6jobth2#92477709-2#06433455-2#57715521-2#36985629", "unix_time": 1620589934.382413}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_6jobth2#92477709-2#06433455-2#57715521-2#36985629", "unix_time": 1620589942.3027985}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_7jobth2#18945967-2#31235906-2#82679283-2#36534583", "unix_time": 1620590006.8866186}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_7jobth2#18945967-2#31235906-2#82679283-2#36534583", "unix_time": 1620590008.0144553}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_7jobth2#18945967-2#31235906-2#82679283-2#36534583", "unix_time": 1620590015.8637197}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_8jobth2#29111520-2#01837077-2#12125340-2#22266274", "unix_time": 1620590158.449817}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_8jobth2#29111520-2#01837077-2#12125340-2#22266274", "unix_time": 1620590159.6909316}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_8jobth2#29111520-2#01837077-2#12125340-2#22266274", "unix_time": 1620590167.5994298}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3b_preagg3_9jobth2#54306553-2#16101385-2#79442787-2#15627817", "unix_time": 1620590312.179609}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3c_preagg3_9jobth2#54306553-2#16101385-2#79442787-2#15627817", "unix_time": 1620590313.3269963}
INFO:circe.py:runtime_stat:{"task_name": "circe", "event": "new_input_file", "filename": "score3a_preagg3_9jobth2#54306553-2#16101385-2#79442787-2#15627817", "unix_time": 1620590321.2487242}
